/**
 * Tests for the admin-dev invoice PDF verifier.
 *
 * These use the sample invoice generated by the frontend at
 * marketing/INVOICE-SAMPLE.pdf, so the parser is exercised against a real
 * package:pdf document rather than a hand-written approximation of one.
 */
process.env.ADMIN_DEV_USER = process.env.ADMIN_DEV_USER || 'admin';
process.env.ADMIN_DEV_PASSWORD = process.env.ADMIN_DEV_PASSWORD || 'dev-secret';

const path = require('path');
const fs = require('fs');

jest.mock('../core/TemporalManager', () => ({
  describeWorkflow: jest.fn(),
  listWorkflows: jest.fn().mockResolvedValue({ workflows: [], total: null, degraded: false }),
  getTaskQueue: jest.fn(),
  getClient: jest.fn(),
  startWorkflow: jest.fn(),
  close: jest.fn(),
}));

const verifier = require('../services/invoicePdfVerifier');

// The sample must exist; generate with
// `flutter test test/sample_invoice_marketing_pdf.dart` from the frontend repo.
const SAMPLE_PATH = path.join(__dirname, '../../../marketing/INVOICE-SAMPLE.pdf');
const sampleExists = fs.existsSync(SAMPLE_PATH);
const sampleBuffer = sampleExists ? fs.readFileSync(SAMPLE_PATH) : null;
const sampleText = sampleExists ? verifier.extractPdfText(sampleBuffer) : '';

// The fixture the sample was rendered from, so field-level expectations are
// explicit rather than reverse-engineered from the output.
const SAMPLE_EXPECTED = {
  invoiceNumber: 'INV-2026-0913-SAMPLE',
  periodStart: '2026-09-07',
  periodEnd: '2026-09-13',
  subtotal: 1541.0,
  tax: 0,
  total: 1541.0,
  hoursCompleted: 18.5,
  itemCount: 5,
};

describe('invoice PDF verifier — extraction', () => {
  beforeAll(() => {
    if (!sampleExists) {
      // eslint-disable-next-line no-console
      console.warn(
        '\n  sample invoice missing — regenerate with:\n' +
          '    cd ../ && flutter test test/sample_invoice_marketing_pdf.dart\n'
      );
    }
  });

  test('extracts text from a FlateDecode content stream', () => {
    if (!sampleExists) return;
    expect(sampleBuffer.slice(0, 5).toString()).toBe('%PDF-');
    expect(sampleText.length).toBeGreaterThan(500);
  });

  test('recovers the invoice header fields', () => {
    if (!sampleExists) return;
    const f = verifier.parseInvoiceFields(sampleText);
    expect(f.invoiceNumber).toBe(SAMPLE_EXPECTED.invoiceNumber);
    expect(f.periodStart).toBe(SAMPLE_EXPECTED.periodStart);
    expect(f.periodEnd).toBe(SAMPLE_EXPECTED.periodEnd);
  });

  test('recovers the financial totals', () => {
    if (!sampleExists) return;
    const f = verifier.parseInvoiceFields(sampleText);
    expect(f.subtotal).toBeCloseTo(SAMPLE_EXPECTED.subtotal, 2);
    expect(f.tax).toBeCloseTo(SAMPLE_EXPECTED.tax, 2);
    expect(f.total).toBeCloseTo(SAMPLE_EXPECTED.total, 2);
    expect(f.hoursCompleted).toBeCloseTo(SAMPLE_EXPECTED.hoursCompleted, 2);
  });

  test('recovers every line item, including repeated support item codes', () => {
    if (!sampleExists) return;
    const f = verifier.parseInvoiceFields(sampleText);
    // Two of the five shifts use the same support item number, which is the
    // normal case; collapsing them would silently under-report the invoice.
    expect(f.items).toHaveLength(SAMPLE_EXPECTED.itemCount);
    const repeated = f.items.filter((i) => i.supportItemNumber === '01_011_0107_1_1');
    expect(repeated).toHaveLength(2);
    expect(repeated.map((i) => i.totalPrice)).toEqual([220.74, 331.11]);
  });
});

describe('invoice PDF verifier — arithmetic', () => {
  const sampleFields = () => verifier.parseInvoiceFields(sampleText);

  test('an unmodified invoice is internally consistent', () => {
    if (!sampleExists) return;
    const checks = verifier.checkArithmetic(sampleFields());
    expect(checks.every((c) => c.passed)).toBe(true);
  });

  test('every check reports a name and a pass state, not just a boolean', () => {
    if (!sampleExists) return;
    const checks = verifier.checkArithmetic(sampleFields());
    checks.forEach((c) => {
      expect(typeof c.name).toBe('string');
      expect(c.name.length).toBeGreaterThan(0);
      expect(typeof c.passed).toBe('boolean');
      expect(c).toHaveProperty('detail');
    });
  });

  test('a doctored total is caught by subtotal + tax=tax total', () => {
    if (!sampleExists) return;
    const f = sampleFields();
    f.total = f.total + 500; // the classic inflate-the-total edit
    const checks = verifier.checkArithmetic(f);
    const failed = checks.filter((c) => !c.passed);
    expect(failed.length).toBeGreaterThan(0);
    expect(failed.some((c) => c.name.includes('Subtotal + tax'))).toBe(true);
  });

  test('a doctored line-item amount is caught by the row reconciliation', () => {
    if (!sampleExists) return;
    const f = sampleFields();
    f.items[0].totalPrice = f.items[0].totalPrice + 100;
    const checks = verifier.checkArithmetic(f);
    expect(checks.some((c) => !c.passed && c.name.includes('reconcile'))).toBe(true);
  });

  test('a doctored subtotal is caught by the items sum', () => {
    if (!sampleExists) return;
    const f = sampleFields();
    f.subtotal = 2000;
    const checks = verifier.checkArithmetic(f);
    expect(checks.some((c) => !c.passed && c.name.includes('Line items sum'))).toBe(true);
  });

  test('a doctored hours total is caught', () => {
    if (!sampleExists) return;
    const f = sampleFields();
    f.hoursCompleted = 99.5;
    const checks = verifier.checkArithmetic(f);
    expect(checks.some((c) => !c.passed && c.name.includes('hours'))).toBe(true);
  });
});

describe('invoice PDF verifier — record comparison', () => {
  const stored = () => ({
    invoiceNumber: 'INV-2026-0913-SAMPLE',
    startDate: new Date('2026-09-07T00:00:00.000Z'),
    endDate: new Date('2026-09-13T00:00:00.000Z'),
    financialSummary: { subtotal: 1541.0, taxAmount: 0, totalAmount: 1541.0 },
    lineItems: [
      { supportItemNumber: '01_011_0107_1_1', quantity: 3, price: 73.58, totalPrice: 220.74 },
      { supportItemNumber: '01_011_0107_1_1', quantity: 4.5, price: 73.58, totalPrice: 331.11 },
      { supportItemNumber: '01_002_0107_1_1', quantity: 5, price: 82.57, totalPrice: 412.85 },
      { supportItemNumber: '01_015_0107_1_1', quantity: 2, price: 81.07, totalPrice: 162.14 },
      { supportItemNumber: '01_013_0107_1_1', quantity: 4, price: 103.54, totalPrice: 414.16 },
    ],
  });

  test('an untouched PDF matches the stored invoice', () => {
    if (!sampleExists) return;
    const r = verifier.compareToRecord(verifier.parseInvoiceFields(sampleText), stored());
    expect(r.matches).toBe(true);
    expect(r.realDiffCount).toBe(0);
  });

  test('a changed amount is reported field by field', () => {
    if (!sampleExists) return;
    const record = stored();
    record.financialSummary.subtotal = 9999;
    record.financialSummary.totalAmount = 9999;
    record.lineItems[0].totalPrice = 999.99;

    const r = verifier.compareToRecord(verifier.parseInvoiceFields(sampleText), record);
    expect(r.matches).toBe(false);
    const fields = r.diffs.map((d) => d.field);
    expect(fields).toContain('subtotal');
    expect(fields).toContain('total');
    expect(fields).toContain('lineItem[0].amount');
    // Every diff carries both sides, so the operator can see what moved.
    r.diffs.filter((d) => d.state === 'differs').forEach((d) => {
      expect(d).toHaveProperty('pdf');
      expect(d).toHaveProperty('stored');
    });
  });

  test('a deleted line item is caught', () => {
    if (!sampleExists) return;
    const record = stored();
    record.lineItems.splice(2, 1);
    const r = verifier.compareToRecord(verifier.parseInvoiceFields(sampleText), record);
    expect(r.matches).toBe(false);
    expect(r.diffs.map((d) => d.field)).toContain('lineItemCount');
  });

  test('fields that could not be parsed are separated from real mismatches', () => {
    if (!sampleExists) return;
    const r = verifier.compareToRecord(verifier.parseInvoiceFields(sampleText), stored());
    // clientName is not emitted by the generator, so it must not be counted as
    // a mismatch — otherwise every invoice looks tampered.
    expect(r.unparsedCount).toBeGreaterThanOrEqual(0);
    expect(r.realDiffCount).toBe(0);
  });
});

describe('invoice PDF verifier — verdict', () => {
  const fields = () => verifier.parseInvoiceFields(sampleText);

  test('a consistent invoice with a watermark is called original', () => {
    const verdict = verifier.buildVerdict({
      arithmetic: { passed: true, checks: [] },
      record: { found: true, matches: true },
      watermark: { present: true },
    });
    expect(verdict.verdict).toBe('original');
    expect(verdict.confidence).toBe('high');
  });

  test('broken arithmetic is called modified regardless of the watermark', () => {
    const verdict = verifier.buildVerdict({
      arithmetic: { passed: false, checks: [] },
      record: { found: true, matches: true },
      watermark: { present: true },
    });
    // The watermark cannot vouch for content, so a document that contradicts
    // itself must not be cleared by one being present.
    expect(verdict.verdict).toBe('modified');
  });

  test('a record mismatch is called out as differing, not ambiguous', () => {
    const verdict = verifier.buildVerdict({
      arithmetic: { passed: true, checks: [] },
      record: { found: true, matches: false },
      watermark: { present: true },
    });
    expect(verdict.verdict).toBe('differs-from-record');
    expect(verdict.confidence).toBe('high');
    expect(verdict.signals).toContain('record-mismatch');
  });

  test('no stored record means self-consistent, not a clean bill', () => {
    const verdict = verifier.buildVerdict({
      arithmetic: { passed: true, checks: [] },
      record: { found: false, matches: null },
      watermark: { present: false },
    });
    // Earlier this reported "consistent-with-record" for an invoice that was
    // never compared to anything — a claim about a comparison that did not
    // happen.
    expect(verdict.verdict).toBe('self-consistent');
    expect(verdict.confidence).toBe('medium');
  });

  test('the verdict never claims the watermark was cryptographically verified', () => {
    const v = verifier.buildVerdict({
      arithmetic: { passed: true, checks: [] },
      record: { found: true, matches: true },
      watermark: { present: true },
    });
    // This is the whole honesty contract of the module: presence is not proof.
    expect(v.claims.watermarkCryptographicallyVerified).toBe(false);
  });

  test('the stated watermark limitations match the implementation', () => {
    expect(verifier.WATERMARK_LIMITS).toEqual({
      coversContentOnly: false,
      serverHasSecret: false,
      persistedOnInvoice: false,
    });
  });
});

describe('invoice PDF verifier — the watermark itself', () => {
  test('documents that the current watermark is absent from issued invoices', () => {
    if (!sampleExists) return;
    // This assertion is deliberately written to describe reality, not intent.
    //
    // The invoice generator computes HMAC(secret, invoiceNumber) and injects it
    // as zero-width characters — but package:pdf's base-14 Helvetica font has
    // no Unicode support, so those code points are dropped by the PDF writer.
    // Until a Unicode font is embedded, NO invoice ever issued carries a
    // watermark. If this test starts failing after a font is added, the
    // watermark has begun working and the limitation can be lifted.
    const raw = sampleBuffer.toString('latin1');
    const zwSequences = ['e2808b', 'e2808c', 'e2808d', 'efbbbf'];
    zwSequences.forEach((hex) => {
      expect(raw.includes(Buffer.from(hex, 'hex').toString('latin1'))).toBe(false);
    });
    expect(verifier.inspectWatermark(sampleText).present).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Route-level behaviour. These need the app, so they are appended after the
// pure-function suites to keep the fast checks first.
// ---------------------------------------------------------------------------
const request = require('supertest');
const app = require('../app');

const authHeader =
  'Basic ' + Buffer.from(`${process.env.ADMIN_DEV_USER}:${process.env.ADMIN_DEV_PASSWORD}`).toString('base64');

describe('admin-dev verify-invoice-pdf route', () => {
  const buildReq = () =>
    request(app)
      .post('/admin-dev/api/ops/verify-invoice-pdf')
      .set('Authorization', authHeader);

  // The CSRF token is minted per page render, so fetch one from the console
  // exactly as a browser would rather than re-deriving it.
  const fetchCsrf = async () => {
    const pageRes = await request(app)
      .get('/admin-dev/ops')
      .set('Authorization', authHeader);
    const m = pageRes.text.match(/<meta name="admin-dev-csrf" content="([0-9a-f]+)">/);
    return m ? m[1] : null;
  };

  test('requires authentication', async () => {
    const res = await request(app).post('/admin-dev/api/ops/verify-invoice-pdf');
    expect(res.status).toBe(401);
  });

  test('requires the CSRF header, and rejects its absence', async () => {
    const res = await buildReq().attach('pdf', sampleBuffer || Buffer.from('%PDF-1.4\n'), {
      filename: 'x.pdf',
      contentType: 'application/pdf',
    });
    expect(res.status).toBe(403);
  });

  test('rejects a non-PDF payload', async () => {
    const csrf = await fetchCsrf();
    expect(csrf).toMatch(/^[0-9a-f]+$/);
    const res = await buildReq()
      .set('x-admin-dev-csrf', csrf)
      .attach('pdf', Buffer.from('this is not a pdf at all'), {
        filename: 'fake.pdf',
        contentType: 'application/pdf',
      });
    expect(res.status).toBe(400);
  });

  test('rejects a request with no file at all', async () => {
    const csrf = await fetchCsrf();
    const res = await buildReq().set('x-admin-dev-csrf', csrf);
    expect(res.status).toBe(400);
  });

  test('accepts a real invoice PDF and returns a structured verdict', async () => {
    if (!sampleExists) return;
    const csrf = await fetchCsrf();
    const res = await buildReq()
      .set('x-admin-dev-csrf', csrf)
      .attach('pdf', sampleBuffer, { filename: 'INVOICE-SAMPLE.pdf', contentType: 'application/pdf' });

    expect(res.status).toBe(200);
    const d = res.body.data;
    // The verdict must carry every signal, and must not claim the watermark was
    // cryptographically verified.
    expect(d).toHaveProperty('verdict.verdict');
    expect(d).toHaveProperty('verdict.signals');
    expect(d.verdict.claims.watermarkCryptographicallyVerified).toBe(false);
    expect(d).toHaveProperty('watermarkLimits');
    expect(d.parsed.invoiceNumber).toBe(SAMPLE_EXPECTED.invoiceNumber);
    // Arithmetic is self-consistent on an untouched document.
    expect(d.arithmetic.passed).toBe(true);
    // The sample invoice number is not in any database, so no record is found —
    // which is a legitimate outcome, not an error.
    expect(d.record.found).toBe(false);
  });
});
