class InvoiceModel {
  final String clientName;
  final String clientEmail;
  final String clientPhone;
  final List<String> clientAddress;
  final String clientBusinessName;
  final List<String> dateList;
  final List<String> startTimeList;
  final List<String> endTimeList;
  final List<String> breakList;
  final List<String> timeList;
  final double totalAmount;
  final String invoiceNumber;
  final List<String>?
      attachedPhotos; // List of photo file paths or base64 strings
  final String? photoDescription; // Optional description for the photos

  InvoiceModel({
    required this.clientName,
    required this.clientEmail,
    required this.clientPhone,
    required this.clientAddress,
    required this.clientBusinessName,
    required this.dateList,
    required this.startTimeList,
    required this.endTimeList,
    required this.breakList,
    required this.timeList,
    required this.totalAmount,
    required this.invoiceNumber,
    this.attachedPhotos,
    this.photoDescription,
  });

  factory InvoiceModel.fromJson(Map<String, dynamic> json) {
    return InvoiceModel(
      clientName: "${json['clientFirstName']} ${json['clientLastName']}",
      clientEmail: json['clientEmail'] ?? '',
      clientPhone: json['clientPhone'] ?? '',
      clientAddress: [
        json['clientAddress'] ?? '',
        json['clientCity'] ?? '',
        json['clientState'] ?? '',
        json['clientZip'] ?? ''
      ],
      clientBusinessName: json['clientBusinessName'] ?? '',
      dateList: List<String>.from(json['dateList'] ?? []),
      startTimeList: List<String>.from(json['startTimeList'] ?? []),
      endTimeList: List<String>.from(json['endTimeList'] ?? []),
      breakList: List<String>.from(json['breakList'] ?? []),
      timeList: List<String>.from(json['Time'] ?? []),
      totalAmount: 0.0, // Calculate this based on your business logic
      invoiceNumber: '', // Will be generated by backend
      attachedPhotos: json['attachedPhotos'] != null
          ? List<String>.from(json['attachedPhotos'])
          : null,
      photoDescription: json['photoDescription'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'clientName': clientName,
      'clientEmail': clientEmail,
      'clientPhone': clientPhone,
      'clientAddress': clientAddress,
      'clientBusinessName': clientBusinessName,
      'dateList': dateList,
      'startTimeList': startTimeList,
      'endTimeList': endTimeList,
      'breakList': breakList,
      'timeList': timeList,
      'totalAmount': totalAmount,
      'invoiceNumber': invoiceNumber,
      'attachedPhotos': attachedPhotos,
      'photoDescription': photoDescription,
    };
  }

  InvoiceModel copyWith({
    String? clientName,
    String? clientEmail,
    String? clientPhone,
    List<String>? clientAddress,
    String? clientBusinessName,
    List<String>? dateList,
    List<String>? startTimeList,
    List<String>? endTimeList,
    List<String>? breakList,
    List<String>? timeList,
    double? totalAmount,
    String? invoiceNumber,
    List<String>? attachedPhotos,
    String? photoDescription,
  }) {
    return InvoiceModel(
      clientName: clientName ?? this.clientName,
      clientEmail: clientEmail ?? this.clientEmail,
      clientPhone: clientPhone ?? this.clientPhone,
      clientAddress: clientAddress ?? this.clientAddress,
      clientBusinessName: clientBusinessName ?? this.clientBusinessName,
      dateList: dateList ?? this.dateList,
      startTimeList: startTimeList ?? this.startTimeList,
      endTimeList: endTimeList ?? this.endTimeList,
      breakList: breakList ?? this.breakList,
      timeList: timeList ?? this.timeList,
      totalAmount: totalAmount ?? this.totalAmount,
      invoiceNumber: invoiceNumber ?? this.invoiceNumber,
      attachedPhotos: attachedPhotos ?? this.attachedPhotos,
      photoDescription: photoDescription ?? this.photoDescription,
    );
  }

  static InvoiceModel empty() {
    return InvoiceModel(
      clientName: '',
      clientEmail: '',
      clientPhone: '',
      clientAddress: [],
      clientBusinessName: '',
      dateList: [],
      startTimeList: [],
      endTimeList: [],
      breakList: [],
      timeList: [],
      totalAmount: 0.0,
      invoiceNumber: '',
      attachedPhotos: null,
      photoDescription: null,
    );
  }
}
