# # Uncomment this line to define a global platform for your project
# platform :ios, '13.0'
#
# # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'
#
# project 'Runner', {
#   'Debug' => :debug,
#   'Profile' => :release,
#   'Release' => :release,
# }
#
# def flutter_root
#   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
#   unless File.exist?(generated_xcode_build_settings_path)
#     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
#   end
#
#   File.foreach(generated_xcode_build_settings_path) do |line|
#     matches = line.match(/FLUTTER_ROOT\=(.*)/)
#     return matches[1].strip if matches
#   end
#   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
# end
#
# require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
#
# flutter_ios_podfile_setup
#
# target 'Runner' do
#   use_frameworks!
#   use_modular_headers!
#
#   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#   target 'RunnerTests' do
#     inherit! :search_paths
#   end
# end
#
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end

platform :ios, '14.0'
use_frameworks!

# Disable CocoaPods analytics to improve build latency
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Firebase dependencies
# pod 'Firebase', '~> 11.4.0'
# Firebase dependencies are managed by Flutter plugins. Do not specify manually unless required.

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install all Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Additional pods or configurations can be added here
end

post_install do |installer|
  # Remove the -G flag from all targets
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
    config.build_settings['OTHER_CFLAGS'] = config.build_settings['OTHER_CFLAGS'].reject { |f| f == '-G' }
    config.build_settings['OTHER_CXXFLAGS'] ||= ['$(inherited)']
    config.build_settings['OTHER_CXXFLAGS'] = config.build_settings['OTHER_CXXFLAGS'].reject { |f| f == '-G' }
  end

  # Apply Flutter-specific build settings to all targets
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Force the minimum iOS version to 14.0 for all targets
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # Special handling for BoringSSL-GRPC
      if target.name == 'BoringSSL-GRPC'
        config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '1'
      end
    end
  end
end
