# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Increment build number"
  lane :increment_build_number do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
  end

  desc "Submit a new Development Build to TestFlight"
  lane :deploy_development do
    # Uncomment when ready to deploy to TestFlight
    # increment_build_number
    # 
    # build_app(
    #   workspace: "Runner.xcworkspace",
    #   scheme: "Development",
    #   export_method: "app-store",
    #   export_options: {
    #     provisioningProfiles: { 
    #       "com.bishal.invoice.dev" => "match AppStore com.bishal.invoice.dev"
    #     }
    #   }
    # )
    # 
    # upload_to_testflight(
    #   skip_waiting_for_build_processing: true
    # )
  end

  desc "Submit a new Production Build to TestFlight"
  lane :deploy_production do
    # Uncomment when ready to deploy to TestFlight
    # increment_build_number
    # 
    # build_app(
    #   workspace: "Runner.xcworkspace",
    #   scheme: "Production",
    #   export_method: "app-store",
    #   export_options: {
    #     provisioningProfiles: { 
    #       "com.bishal.invoice" => "match AppStore com.bishal.invoice"
    #     }
    #   }
    # )
    # 
    # upload_to_testflight(
    #   skip_waiting_for_build_processing: true
    # )
  end
end